[package]
name = "pallet-staking-runtime-api"
version = "22.0.0"
authors.workspace = true
edition.workspace = true
license = "MIT"
homepage = "https://hippius.com"
repository = "https://github.com/thenervelab/thebrain"
description = "RPC runtime API for transaction payment FRAME pallet (polkadot v1.15.0)"
readme = "README.md"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = ["derive"], workspace = true }
sp-api.workspace = true
sp-staking.workspace = true

[features]
default = ["std"]
std = ["codec/std", "sp-api/std", "sp-staking/std"]
