name: Docker Build Test

on: [push, pull_request]

jobs:
  build-miner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Image  
        run: |
          docker build -t hippius-miner -f Dockerfile-Miner .
          echo "Image built successfully"